{% set name = "equinox" %}
{% set version = "0.13.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 509ad744ff99b7c684d45230d6890f9e78eac1a556d7a06db1eff664a3cac74f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.4.38,!=0.7.0,!=0.7.1
    - jaxtyping >=0.2.20
    - typing_extensions >=4.5.0
    - wadler-lindig >=0.1.0

test:
  imports:
    - equinox
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/patrick-kidger/equinox
  summary: Neural Networks in JAX.
  description: |
    Callable PyTrees and filtered JIT/grad transformations
    => neural networks in JAX.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.kidger.site/equinox/
  dev_url: https://github.com/patrick-kidger/equinox

extra:
  recipe-maintainers:
    - maresb
    - dhirschfeld
